### ISSUE TITLE
PHP 8.X

### ISSUE THREAD

**Issue by s7thamon** [robertogallea/eloquent-api#4]
This looks fantastic! I've used vanilla sushi before to handle this but the package definitely takes it further. Any plans to support PHP 8 (& laravel 9)?

**Comment by robertogallea** [comment]
Hi! Thank you for your appreciation! I just update the package to support PHP 8.x and Laravel 8-9. Please let me know if there is any issue.

**Comment by s7thamon** [comment]
Yup it pulls down great, thanks very much! Looking to see how I can disable ssl verification and if data happens to be wrapped in more than one resource field - I'll keep playing with it.
